version: "3"
services:
  db:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1165
      MYSQL_DATABASE: e-shop
      MYSQL_USER: root
      MYSQL_PASSWORD: 1165

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 1165
      UPLOAD_LIMIT: 3000000000
    ports:
      - "1000:80"
    depends_on:
      - db
  web:
    image: gits5622/eshop
    depends_on:
      - db
    ports:
      - "8000:80"
